### PR TITLE
Autos!

### LINKED ISSUE #170: Create Autos
So... what autos do we want? Here's my list (but feel free to edit it as more ideas come up/priorities change)

STARTING NEAR SPIKE MARKS
- [ ] Preload into Speaker (then end the auto)
- [ ] Preload into Amp (then end the auto)
- [ ] 4 note Wing-only auto (the robot drives in a straight line)
- [ ] 4+ Wing + Centerline auto? 😳

STARTING CENTER-FIELD
- [ ] Preload into Speaker (then end the auto)
- [ ] Shoot into speaker, then go centerline (up)
- [ ] Shoot into speaker, then go centerline (down)

STARTING BOTTOM FIELD
- [ ] Preload into Speaker (then end the auto)
- [ ] Shoot into speaker, then go centerline (up)

### LINKED ISSUE #202: Tune auto swerve properly
🍣
Swerve

### LINKED ISSUE #265: Tune iCAT PID

### LINKED ISSUE #269: Invert presets for opposite alliance

### LINKED ISSUE #270: Add transfer game piece check if transfer roller encoder counts to determine if game piece shot

### LINKED ISSUE #273: Change intake pivot to have zero at bottom

### PR DESCRIPTION
**Pull request by alicekuznetsov**

### CODE REVIEW

**Comment by alicekuznetsov** [comment]
AdvantageScope_(WPILib)_320sXa8u7M
robot is preheating in the microwave

**Comment by alicekuznetsov** [comment]
WORTH IT (ignore the shooter pose being wrong bc i lowkey don't care)
AdvantageScope_(WPILib)_zM0tKhIg3D

**Comment by alicekuznetsov** [comment]
image
i was gonna upload a gif of the auto working but its too big :( just trust me

**Comment by alicekuznetsov** [comment]
still need to write code to get the locking to actually lock in autonomous but i must unfortunately address my Advanced Placement English Language and Composition essay at this time

**Review by TaylerUva — APPROVED** [review]

**Pull request merged**
